import { z } from "zod";

export const resultFormSchema = z.object({
    queryInformationLTFullName: z.string().optional(),
    queryInformationLTIndexNo: z.string().optional(),
    queryInformationLTAddress: z.string().optional(),
    queryInformationLTBusinessName: z.string().optional(),
    queryInformationLTInputDate: z.string().optional(),
    queryInformationStandardServeTo: z.string().optional(),
    queryInformationStandardDefendants: z.string().optional(),
    queryInformationStandardPlaintiff: z.string().optional(),
    serviceResultInputDate: z.string().optional(),
    serviceResultScvType: z.string().optional(),
    serviceResultClientId: z.string().optional(),
    serviceResultJobNo: z.string().regex(/^\d+$/, { message: "Index No  must be number" }),
    serviceResultServerId: z.string().optional(),
    serviceResultResults: z.string().optional(),
    serviceResultDateOfService: z.string().optional(),
    serviceResultTimeService: z.string().optional(),
    serviceResultFirstTimeOfService: z.string().optional(),
    serviceResultFirstAttemptDate: z.string().optional(),
    serviceResultSecondTimeOfService: z.string().optional(),
    serviceResultSecondAttemptDate: z.string().optional(),
    serviceResultThirdTimeOfService: z.string().optional(),
    serviceResultThirdAttemptDate: z.string().optional(),
    serviceResultlTServed: z.string().optional(),
    serviceResultlTNotServed: z.string().optional(),
    serviceResultRecipientTitle: z.string().optional(),
    serviceResultDoor: z.string().optional(),
    serviceResultRecipient: z.string().optional(),
    serviceResultDoorLocks: z.string().optional(),
    serviceResultEntry: z.string().optional(),
    serviceResultWall: z.string().optional(),
    serviceResultFloor: z.string().optional(),
    serviceResultLock: z.string().optional(),
    serviceResultOtherDescription: z.boolean().optional(),
    serviceResultSex: z.string().optional(),
    serviceResultSkinColor: z.string().optional(),
    serviceResultHair: z.string().optional(),
    serviceResultAge: z.string().optional(),
    serviceResultHeight: z.string().optional(),
    serviceResultWeight: z.string().optional(),
    serviceResultOtherFeatures: z.string().optional(),
    serviceResultDateOfMailing: z.string().optional(),
    serviceResultDateOfNotary: z.string().optional(),
}
)
