
import { optional, z } from "zod"

export const LTFormSchema = z.object({
    oLTDescription: z.string().optional(),
    caseNo: z.any(),
    oLTIndexNo: z.any(),
    inputDate: z.any(),
    jobNo: z.any(),
    clientId: z.string().optional(),
    serviceType: z.string().optional(),
    timeTrip: z.string().optional(),
    caption: z.any(),
    lTServiceType: z.any(),
    lTSFirstName: z.string().optional(),
    lTSBusinessName: z.string().optional(),
    lTSAddress: z.string().optional(),
    lTSApt: z.string().optional(),
    lTSCity: z.string().optional(),
    lTSState: z.string().optional(),
    lTSZip: z.string().optional(),
    lTSDescription: z.string().optional(),
    noOfAddLMailings: z.string().optional(),
    mailingAddresses: z.string().optional(),
    lTSCityLongitude: z.string().optional(),
    lTSCityLatitude: z.string().optional(),
    //STANDARD FORM SCHEMA
    standardServiceType: z.boolean().optional(),
    oSSTIndexNo: z.string().optional(),
    oSSTDescription: z.string().optional(),
    sSDCourt: z.string().optional(),
    sSDDefendants: z.string().optional(),
    sSDPlaintiff: z.string().optional(),
    sSDCountry: z.string().optional(),
    // RESULT FORM SCHEMA
    startDate: z.string().optional(),
    endDate: z.string().optional(),

    queryInformationLTFullName: z.string().optional(),
    queryInformationLTIndexNo: z.string().optional(),
    queryInformationLTAddress: z.string().optional(),
    queryInformationLTBusinessName: z.string().optional(),
    queryInformationLTInputDate: z.string().optional(),
    queryInformationStandardServeTo: z.string().optional(),
    queryInformationStandardDefendants: z.string().optional(),
    queryInformationStandardPlaintiff: z.string().optional(),
    serviceResultInputDate: z.string().optional(),
    serviceResultScvType: z.string().optional(),

    serviceResultJobNo: z.string().optional(),
    serviceResultServerId: z.string().optional(),
    serviceResultResults: z.string().optional(),
    serviceResultDateOfService: z.string().optional(),
    serviceResultTimeOfService: z.any(),
    serviceResultFirstTimeOfService: z.any(),
    serviceResultFirstAttemptDate: z.string().optional(),
    serviceResultSecondTimeOfService: z.any(),
    serviceResultSecondAttemptDate: z.string().optional(),
    serviceResultThirdTimeOfService: z.any(),
    serviceResultThirdAttemptDate: z.string().optional(),
    serviceResultlTServed: z.string().optional(),
    serviceResultlTNotServed: z.string().optional(),
    serviceResultRecipientTitle: z.string().optional(),
    serviceResultDoor: z.string().optional(),
    serviceResultRecipient: z.string().optional(),
    serviceResultDoorLocks: z.string().optional(),
    serviceResultEntry: z.string().optional(),
    serviceResultWall: z.string().optional(),
    serviceResultFloor: z.string().optional(),
    serviceResultLock: z.string().optional(),
    serviceResultOtherDescription: z.boolean().optional(),
    serviceResultSex: z.string().optional(),
    serviceResultSkinColor: z.string().optional(),
    serviceResultHair: z.string().optional(),
    serviceResultAge: z.string().optional(),
    serviceResultHeight: z.string().optional(),
    serviceResultWeight: z.string().optional(),
    serviceResultOtherFeatures: z.string().optional(),
    serviceResultDateOfMailing: z.string().optional(),
    serviceResultDateOfNotary: z.string().optional(),
    substituteDeliveredTo: z.string().optional(),
    corporateRecipient: z.string().optional(),
})